//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpaceObject
    {
        public int Id { get; set; }
        public int SpaceObjectTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Mass { get; set; }
        public double Distance { get; set; }
        public double Radius { get; set; }
    
        public virtual SpaceObjectType SpaceObjectType { get; set; }
    }
}
