//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpaceObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpaceObject()
        {
            this.SpaceObject1 = new HashSet<SpaceObject>();
        }
    
        public int Id { get; set; }
        public int SpaceObjectTypeId { get; set; }
        public string Name { get; set; }
        public double Distance { get; set; }
        public double Radius { get; set; }
        public int OwnerId { get; set; }
        public double Mass { get; set; }
        public string Description { get; set; }
        public string WikiLink { get; set; }
        public byte[] MainImage { get; set; }
        public byte[] OrbitImage { get; set; }
        public Nullable<long> OrbitPeriod { get; set; }
        public Nullable<long> SiderealPeriod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpaceObject> SpaceObject1 { get; set; }
        public virtual SpaceObject SpaceObject2 { get; set; }
        public virtual SpaceObjectType SpaceObjectType { get; set; }
    }
}
